swagger: 2.0
info:
  version: 1.0.0-SNAPSHOT
  title: Quizzly / Author
  description: |
    Authoring online tests
    
    Response with status `422` means the request didn't pass validation.
    For body of response see `POST /v1/quiz`
host: ${http.host}:${http.port}
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
  - multipart/form-data
  - application/x-www-form-urlencoded
produces:
  - application/json
  - image/png
paths:

  /v1/quiz:
    $ref: points/v1/v1_quiz.yaml
  /v1/quiz/{id}:
    $ref: points/v1/v1_quiz_ID.yaml
  /v1/quiz/{id}/authors/{authorId}:
    $ref: points/v1/v1_quiz_ID_authors_AUTHORID.yaml
  /v1/quiz/{id}/inspectors/{inspectorId}:
    $ref: points/v1/v1_quiz_ID_inspectors_INSPECTORID.yaml
  /v1/quiz/{id}/ready:
    $ref: points/v1/v1_quiz_ID_ready.yaml
  /v1/quiz/{id}/resolve:
    $ref: points/v1/v1_quiz_ID_resolve.yaml
  /v1/section/{id}:
    $ref: points/v1/v1_section_ID.yaml
  /v1/section/{id}/items:
    $ref: points/v1/v1_section_ID_items.yaml
  /v1/section/{id}/items/{itemId}:
    $ref: points/v1/v1_section_ID_items_ITEMID.yaml
  /v1/staff:
    $ref: points/v1/v1_staff.yaml
